---

- name: "Adding Python PPA"
  become: yes
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present

- name: "Install Python"
  become: yes
  apt:
    name: [ "python{{ python_version }}", "python{{ python_version }}-dev", "python{{ python_version }}-distutils" ]
    state: latest
    update_cache: yes

- name: "Check pip version"
  command: "pip{{ python_version}} --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.local/bin"

- name: "Install pip"
  include_tasks: "pip.yml"
  when: pip_is_installed.rc != 0
